version: '3.6'
services:
  iris:
    image: containers.intersystems.com/intersystems/iris-community:latest-cd
    restart: no
    command: /iris-main
      - -a /home/irisowner/dev/ascript.sh
      - --ISCAgent false
    ports: 
      - 41773:1972
      - 42773:52773
    volumes:
      - ./:/home/irisowner/dev

